# -*- coding: utf-8 -*-
"""Barras Normalizadas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kh_iDaBE2e51tIs2-ZyFWjtiqxCdUhMq
"""

#Barras Normalizadas customer personality
from visualizacion_segmentos import plot_barras_normalizadas

# Opcional: diccionario con nombres
nombres = {
    0: "Tradicionales",
    1: "Desconectados",
    2: "Alto Valor",
    3: "Estrella"
}

plot_barras_normalizadas(
    df,
    cluster_col='Cluster',
    variables=['Income', 'Age', 'Total_Spent', 'Total_Purchases', 'Children', 'Recency'],
    nombres_clusters=nombres
)