# -*- coding: utf-8 -*-
"""cargar_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jg_wJ-IwR9vSJhEVFpI5B4zYE5_m91lj
"""

#@title Cargar Datos customer personality
import pandas as pd

def cargar_datos(ruta_csv, separador="\t"):
    return pd.read_csv(ruta_csv, sep=separador)