# -*- coding: utf-8 -*-
"""clustering_modelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQAAQkC9DO77ePMxBgmVPJZb6zMdr2W_
"""

#clustering_modelo cutomer personality
from sklearn.cluster import KMeans

def entrenar_kmeans(data, n_clusters=4):
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    labels = kmeans.fit_predict(data)
    return kmeans, labels