# -*- coding: utf-8 -*-
"""feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gd9FiEWlqvEC6U7TzqDLJ_b5uIFhZGBs
"""

#@title 3 feature_engineering
import pandas as pd
from sklearn.preprocessing import StandardScaler

def codificar_y_escalar(df):
    df_encoded = pd.get_dummies(df, columns=['Education','Marital_Status'], drop_first=True)
    scaler = StandardScaler()
    df_scaled = pd.DataFrame(scaler.fit_transform(df_encoded), columns=df_encoded.columns)
    return df_scaled, scaler