# -*- coding: utf-8 -*-
"""Limpieza_de_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDXMyLRMP1wxhYCjPET7lZTMzaE7peBA
"""

#@title limpieza de datos customer personality
def limpiar_datos(df):
    df = df.copy()
    df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], dayfirst=True)
    df['Customer_Since_Days'] = (df['Dt_Customer'].max() - df['Dt_Customer']).dt.days
    df['Age'] = 2025 - df['Year_Birth']
    df['Children'] = df['Kidhome'] + df['Teenhome']
    df['Total_Spent'] = df[['MntWines','MntFruits','MntMeatProducts','MntFishProducts','MntSweetProducts','MntGoldProds']].sum(axis=1)
    df['Total_Purchases'] = df[['NumWebPurchases','NumCatalogPurchases','NumStorePurchases']].sum(axis=1)
    df['Campaigns_Accepted'] = df[['AcceptedCmp1','AcceptedCmp2','AcceptedCmp3','AcceptedCmp4','AcceptedCmp5']].sum(axis=1)
    df.drop(columns=[
        'ID', 'Year_Birth', 'Dt_Customer',
        'Kidhome', 'Teenhome',
        'Z_CostContact', 'Z_Revenue',
        'AcceptedCmp1','AcceptedCmp2','AcceptedCmp3','AcceptedCmp4','AcceptedCmp5',
        'Response',
        'MntWines','MntFruits','MntMeatProducts','MntFishProducts','MntSweetProducts','MntGoldProds',
        'NumWebPurchases','NumCatalogPurchases','NumStorePurchases'
    ], inplace=True)
    df.drop_duplicates(inplace=True)
    df['Income'] = df['Income'].fillna(df['Income'].median())
    df['Marital_Status'] = df['Marital_Status'].replace({'Alone':'Other', 'Absurd':'Other', 'YOLO':'Other'})
    return df