# -*- coding: utf-8 -*-
"""prediccion_nuevos_clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hm9R5RnTD_9XhrcOwGIE8-jDSrzZQadd
"""

# prediccion_nuevos_clientes
def predecir_segmento(modelo, scaler, df_nuevo):
    df_nuevo_scaled = scaler.transform(df_nuevo)
    return modelo.predict(df_nuevo_scaled)