# -*- coding: utf-8 -*-
"""Radar Plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s2gGA68Jj4kZdIEpnMdsEPzrQc5oEInT
"""

#Radar Plot customer personality
from visualizacion_segmentos import plot_radar

plot_radar(
    df,
    cluster_col='Cluster',
    variables=['Income', 'Age', 'Total_Spent', 'Total_Purchases', 'Children', 'Recency'],
    titulo="Comparativa de segmentos"
)